#!/usr/bin/env python3
"""Offline Natural Earth derivation: explicit local inputs, never downloads.

verify SOURCE_DIR compares every coordinate/name/priority and exact generated bytes.
emit SOURCE_DIR writes constants to stdout; it never rewrites product files.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re

COMMIT = 'f1890d9f152c896d250a77557a5751a93d494776'
INPUTS = (
    ('ne_110m_admin_0_boundary_lines_land.geojson', 'd42479fd79552cca4eec7f85fcdca717a790d29ff06be7676f1af0568c6d3f7c', 331),
    ('ne_110m_admin_0_countries.geojson', '6866c877d39cba9c357620878839b336d569f8c662d3cfab4cb1dbe2d39c977f', 177),
    ('ne_110m_populated_places.geojson', 'a86028b083182b68c7620fc6e1a8a47ee547cb9cd2fb62ccbb78bea786440899', 243),
)

def derive(directory):
    sources = []
    for name, digest, count in INPUTS:
        data = (directory / name).read_bytes()
        if hashlib.sha256(data).hexdigest() != digest:
            raise ValueError('Pinned input hash mismatch: ' + name)
        features = json.loads(data)['features']
        assert len(features) == count
        sources.append(features)
    borders = []
    for feature in sources[0]:
        g = feature['geometry']
        assert g['type'] in ('LineString', 'MultiLineString')
        borders.extend([g['coordinates']] if g['type'] == 'LineString' else g['coordinates'])
    countries, cities = [], []
    for feature in sources[1]:
        p = feature['properties']
        countries.append([p['LABEL_X'], p['LABEL_Y'], p.get('NAME_KO') or p['NAME_EN'], p['LABELRANK']])
    for feature in sources[2]:
        assert feature['geometry']['type'] == 'Point'
        p = feature['properties']
        cities.append([*feature['geometry']['coordinates'], p.get('NAME_KO') or p['NAME_EN'], p['POP_MAX']])
    assert len(borders) == 333 and sum(map(len, borders)) == 3108
    return dict(BORDERS=borders, COUNTRIES=countries, CITIES=cities)

def encode(value):
    return json.dumps(value, ensure_ascii=False, separators=(',', ':'))

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('operation', choices=('emit', 'verify'))
    parser.add_argument('source_dir', type=Path)
    parser.add_argument('--module', type=Path, default=Path(__file__).resolve().parents[1] / 'frontend/geo-map.js')
    args = parser.parse_args()
    data = derive(args.source_dir)
    if args.operation == 'emit':
        for name, value in data.items():
            print(f'export const {name} = {encode(value)};')
    else:
        module = args.module.read_text()
        for name, value in data.items():
            match = re.search(r'^export const ' + name + r' = (.*);$', module, re.M)
            assert match is not None, name + ': missing embedded data'
            raw = match[1]
            assert json.loads(raw) == value, name + ': source value mismatch'
            assert raw == encode(value), name + ': deterministic byte mismatch'
        print(json.dumps({'commit': COMMIT, 'inputs': [{'file': n, 'sha256': h, 'features': c} for n, h, c in INPUTS],
                          'verified': {n: {'records': len(v), 'sha256': hashlib.sha256(encode(v).encode()).hexdigest()} for n, v in data.items()},
                          'border_parts': 333, 'border_vertices': 3108, 'every_coordinate_name_priority': True}))

if __name__ == '__main__':
    main()
